Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using new_project.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;



namespace new_project.Controllers
{
    public class AdminPanelController : Controller
    {
        private SignInManager<User> signInManager;
        private UserManager<User> userManager;
       public AdminPanelController(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }



      public IActionResult Login(string returnUrl)
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(RegisterViewModel? model, string returnUrl)
        {
            if(ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.userName, model.password, true, false);


                if (String.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction("", "Home");
                }
                else
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Privacy", "Home");
            }
            return View(model);
        }
        public IActionResult Logout()
        {
            signInManager.SignOutAsync().GetAwaiter().GetResult();
            return RedirectToAction("", "Home");

        }

        public IActionResult Register()
        {
            return View();
        } 



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if(ModelState.IsValid)
            {
                var result = await userManager.FindByNameAsync(model.userName);
                if(result == null)
                {
                    var newUser = new User(model.userName);
                    newUser.Email = model.email;
                    newUser.role = model.role;
                    var result1 = await userManager.CreateAsync(newUser,model.password);
                    if(result1.Succeeded)
                    {
                        userManager.AddToRoleAsync(newUser, model.role.ToString()).GetAwaiter().GetResult();
                        signInManager.SignInAsync(newUser, true).GetAwaiter().GetResult();
                    }
                    return RedirectToAction("", "Home");
                }
                
            }
            return View(model);
        }

    }
}

Views/AdminPanel/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model NewRoleViewModel



@using (Html.BeginForm("Create", "AdminPanel", FormMethod.Post))
{
    <h1>@Html.EditorFor(model => model.roleName)</h1>
    @for (int i = 0; i < Model.listOfPermissions.Count; i++)
    {
        @Html.DisplayFor(model => model.listOfPermissions[i].name)
        @Html.HiddenFor(model => model.listOfPermissions[i].name)
        @Html.CheckBoxFor(model => model.listOfPermissions[i].selected)
        <br>
    }
    <input type="submit" value="Submit" />
}

Views/AdminPanel/Index.cshtml
@model IEnumerable<new_project.Models.Role>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NormalizedName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConcurrencyStamp)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NormalizedName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConcurrencyStamp)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>